objects/Doctor__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>country__c</fullName>
        <label>country</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <label>id</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>licenseNumber__c</fullName>
        <label>licenseNumber</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>name__c</fullName>
        <label>name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>streetNumber__c</fullName>
        <label>streetNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>surname__c</fullName>
        <label>surname</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>town__c</fullName>
        <label>town</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Hospital__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>country__c</fullName>
        <label>country</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <label>id</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>name__c</fullName>
        <label>name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>streetNumber__c</fullName>
        <label>streetNumber</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>town__c</fullName>
        <label>town</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Hospital</label>
    <nameField>
        <label>Hospital Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hospitals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HospitalDoctors__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>doctorId__c</fullName>
        <externalId>true</externalId>
        <label>doctorId</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hospitalId__c</fullName>
        <externalId>true</externalId>
        <label>hospitalId</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <label>id</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>HospitalDoctors</label>
    <nameField>
        <label>Hospital Doctors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HospitalDoctorsList</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/queriesTasks.cls
public with sharing class queriesTasks {
	
	public static List<Doctor__c> getHiredDoctors(){
		List<HospitalDoctors__c> hospitaldoctors = [select HospitalDoctors__c.doctorId__c from HospitalDoctors__c];
		List<Decimal> ids = new List<Decimal>();
		for(HospitalDoctors__c hosdoc : hospitaldoctors){
			ids.add(hosdoc.doctorId__c);
		}
		List <Doctor__c> doctors = [select Doctor__c.name__c, Doctor__c.surname__c, Doctor__c.id__c from Doctor__c where Doctor__c.id__c in :ids];
		return doctors;
	}
    
    public static List<Doctor__c> getNotHiredDoctors(){
		List<HospitalDoctors__c> hospitaldoctors = [select HospitalDoctors__c.doctorId__c from HospitalDoctors__c];
		List<Decimal> ids = new List<Decimal>();
		for(HospitalDoctors__c hosdoc : hospitaldoctors){
			ids.add(hosdoc.doctorId__c);
		}
		List <Doctor__c> doctors = [select Doctor__c.name__c, Doctor__c.surname__c, Doctor__c.id__c from Doctor__c where Doctor__c.id__c not in :ids];
		return doctors;
	}
	
	public static List<Hospital__c> getHospitalsWithoutDoctors(){
		List<HospitalDoctors__c> hospitaldoctors = [select HospitalDoctors__c.hospitalId__c from HospitalDoctors__c];
		List<Decimal> ids = new List<Decimal>();
		for(HospitalDoctors__c hosdoc : hospitaldoctors){
			ids.add(hosdoc.hospitalId__c);
		}
		List <Hospital__c> hospitals = [select Hospital__c.name__c,Hospital__c.id__c from Hospital__c where Hospital__c.id__c not in :ids];
		return hospitals;
	}
	
	public static AggregateResult[] getCountHospitals(){
		AggregateResult[] aggRes = [select Hospital__c.town__c, count(Hospital__c.id__c) from Hospital__c group by Hospital__c.town__c];
		return aggRes;
	}
	
	public static List<Doctor__c> getADoctors(){
		List <Doctor__c> doctors = [select Doctor__c.name__c, Doctor__c.surname__c, Doctor__c.id__c from Doctor__c where Doctor__c.surname__c like 'A%'];
		return doctors;
	}
	
	public static List<Hospital__c> getHospByCountry(){
		List <Hospital__c> hospitals = [select Hospital__c.name__c,Hospital__c.streetNumber__c, Hospital__c.country__c from Hospital__c where Hospital__c.streetNumber__c > 5 and (Hospital__c.country__c = 'Polska' or Hospital__c.country__c = 'Niemcy') limit 5];
		return hospitals;
	}
	
	public static List<Doctor__c> getSortedDoctors(){
		List <Doctor__c> doctors = [select Doctor__c.name__c, Doctor__c.surname__c, Doctor__c.id__c from Doctor__c order by Doctor__c.surname__c limit 10];
		return doctors;
	}
	
	public static List<Doctor__c> getSortedDoctorsThirdTen(){
		List <Doctor__c> doctors = [select Doctor__c.name__c, Doctor__c.surname__c, Doctor__c.id__c from Doctor__c order by Doctor__c.surname__c limit 10 offset 20];
		return doctors;
	}
	
	public static List<Doctor__c> getMichalAndPawel(){
		List <Doctor__c> doctors = [select Doctor__c.name__c, Doctor__c.surname__c, Doctor__c.id__c from Doctor__c where Doctor__c.name__c = 'Michal' or Doctor__c.name__c = 'Pawel'];
		return doctors;
	}
	
	public static List<Doctor__c> getHiredDoctorsInAHospital(){
		List<Hospital__c> hospitals = [select Hospital__c.id__c from Hospital__c where Hospital__c.name__c like 'A%'];
		List<Decimal> hosId = new List<Decimal>();
		for(Hospital__c hos : hospitals){
			hosId.add(hos.id__c);
		}
		List<HospitalDoctors__c> hospitaldoctors = [select HospitalDoctors__c.doctorId__c from HospitalDoctors__c where HospitalDoctors__c.hospitalId__c in :hosId];
		List<Decimal> ids = new List<Decimal>();
		for(HospitalDoctors__c hosdoc : hospitaldoctors){
			ids.add(hosdoc.doctorId__c);
		}
		List <Doctor__c> doctors = [select Doctor__c.name__c, Doctor__c.surname__c, Doctor__c.id__c from Doctor__c where Doctor__c.id__c in :ids];
		return doctors;
	}
	
	public static List<Doctor__c> getDocByLicNumber(){
		List <Doctor__c> doctors = [select Doctor__c.name__c, Doctor__c.surname__c, Doctor__c.id__c from Doctor__c where Doctor__c.licenseNumber__c > '10000' and Doctor__c.licenseNumber__c < '50000'];
		return doctors;
	}
	
}