objects/Doctor__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>id__c</fullName>
        <label>id</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>name__c</fullName>
        <label>name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>surname__c</fullName>
        <label>surname</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DoctorsListController.cls
public with sharing class DoctorsListController {
    public List<Doctor__c> doctors {get; set;}
    
    public DoctorsListController() {
    	doctors = [SELECT Doctor__c.id__c, Doctor__c.name__c, Doctor__c.surname__c FROM Doctor__c];
    }
    
    public PageReference goToAddNewDoctor(){
    	PageReference Page = new PageReference('/apex/AddNewDoctor');
	    Page.setRedirect(true);
	    return Page;
    }
    
    public PageReference goToMainPage(){
    	PageReference Page = new PageReference('/apex/MainPage');
	    Page.setRedirect(true);
	    return Page;
    }
    
}