objects/Doctor__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>availableDate__c</fullName>
        <label>availableDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>country__c</fullName>
        <label>country</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>department__c</fullName>
        <label>department</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eMail__c</fullName>
        <label>eMail</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>homeConsult__c</fullName>
        <defaultValue>false</defaultValue>
        <label>homeConsult</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>houseNumber__c</fullName>
        <label>houseNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <label>id</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>isAvailable__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isAvailable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>licenseNumber__c</fullName>
        <label>licenseNumber</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>name__c</fullName>
        <label>name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>partTime__c</fullName>
        <defaultValue>false</defaultValue>
        <label>partTime</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>position__c</fullName>
        <label>position</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>postalCode__c</fullName>
        <label>postalCode</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>privatePhone__c</fullName>
        <label>privatePhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>streetNumber__c</fullName>
        <label>streetNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>street__c</fullName>
        <label>street</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>supervisor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>supervisor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>surname__c</fullName>
        <label>surname</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>title__c</fullName>
        <label>title</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>town__c</fullName>
        <label>town</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>workPhone__c</fullName>
        <label>workPhone</label>
        <type>Phone</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DoctorManaging.cls
public with sharing class DoctorManaging {
	
    public static void addDoctor(Decimal id, String name, String surname, String title, String licenseNumber, String position, String department, Boolean supervisor, String workPhone, String privatePhone, String email, String country, String town, String street, Decimal streetNumber, Decimal houseNumber, String postalCode, Boolean isAvailable, Date availableDate, String status, Boolean partTime, Boolean homeConsulting){
    	Doctor__c doctor = new Doctor__c(Name='Doctor', id__c=id, surname__c = surname, name__c = name, title__c = title, licenseNumber__c = licenseNumber, position__c = position, department__c = department, supervisor__c = supervisor, workPhone__c=workPhone, privatePhone__c = privatePhone, eMail__c = email, country__c = country, town__c = town, street__c = street, streetNumber__c = streetNumber, houseNumber__c = houseNumber, postalCode__c = postalCode, isAvailable__c = isAvailable, availableDate__c = availableDate, status__c = status, partTime__c = partTime, homeConsult__c = homeConsulting);
    	insert doctor;
    	system.debug(doctor);
    }
    
    public static void deleteDoctor(Decimal id){
    	List<Doctor__c> doctors = [select id__c, surname__c, name__c, title__c, licenseNumber__c, position__c, department__c, workPhone__c, privatePhone__c, eMail__c, country__c, street__c, streetNumber__c, houseNumber__c, postalCode__c, isAvailable__c, availableDate__c, status__c, partTime__c, homeConsult__c from Doctor__c where id__c = :id limit 1];
    	if(!doctors.isEmpty()){
    		Doctor__c doctor = doctors[0];
    		delete doctor;
    	}
    }
    
    public static void updateDoctor(Decimal id, String name, String surname, String title, String licenseNumber, String position, String department, Boolean supervisor, String workPhone, String privatePhone, String email, String country, String town, String street, Decimal streetNumber, Decimal houseNumber, String postalCode, Boolean isAvailable, Date availableDate, String status, Boolean partTime, Boolean homeConsulting){
    	List<Doctor__c> doctors = [select id__c, surname__c, name__c, title__c, licenseNumber__c, position__c, department__c, supervisor__c, workPhone__c, privatePhone__c, eMail__c, country__c, street__c, streetNumber__c, houseNumber__c, postalCode__c, isAvailable__c, availableDate__c, status__c, partTime__c, homeConsult__c from Doctor__c where id__c = :id limit 1];
    	if(!doctors.isEmpty()){
    		Doctor__c doctor = doctors[0];
    		doctor.name__c = name;
    		doctor.surname__c = surname;
    		doctor.title__c = title;
    		doctor.licenseNumber__c = licenseNumber;
    		doctor.position__c = position;
    		doctor.department__c = department;
    		doctor.workPhone__c = workPhone;
    		doctor.privatePhone__c = privatePhone;
    		doctor.eMail__c = email;
    		doctor.country__c = country;
    		doctor.street__c = street;
    		doctor.streetNumber__c = streetNumber;
    		doctor.houseNumber__c = houseNumber;
    		doctor.postalCode__c = postalCode;
    		doctor.isAvailable__c = isAvailable;
    		doctor.availableDate__c = availableDate;
    		doctor.status__c = status;
    		doctor.partTime__c = partTime;
    		doctor.homeConsult__c = homeConsulting;
    		update doctor;
    		system.debug(doctor);
    	}
    }
}