objects/Hospital__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>chiefOfMedicine__c</fullName>
        <label>chiefOfMedicine</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>country__c</fullName>
        <label>country</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>faxNumber1__c</fullName>
        <label>faxNumber1</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>faxNumber2__c</fullName>
        <label>faxNumber2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <label>id</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>name__c</fullName>
        <label>name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>phoneNumber1__c</fullName>
        <label>phoneNumber1</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>phoneNumber2__c</fullName>
        <label>phoneNumber2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>postalCode__c</fullName>
        <label>postalCode</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>salesRep__c</fullName>
        <label>salesRep</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>streetNumber__c</fullName>
        <label>streetNumber</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>street__c</fullName>
        <label>street</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>teachingHospital__c</fullName>
        <defaultValue>true</defaultValue>
        <label>teachingHospital</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>town__c</fullName>
        <label>town</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Hospital</label>
    <nameField>
        <label>Hospital Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hospitals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HospitalDetailsController.cls
public with sharing class HospitalDetailsController {
    public Hospital__c hospital {get; set;}
	public String hosId {get;set; }
	
	public HospitalDetailsController(){
		hosId = ApexPages.CurrentPage().getparameters().get('id');
		Decimal id = Decimal.valueOf(hosId);
		hospital = [select Hospital__c.id__c, Hospital__c.name__c, Hospital__c.country__c, Hospital__c.town__c, Hospital__c.street__c, Hospital__c.streetNumber__c, Hospital__c.postalCode__c, Hospital__c.phoneNumber1__c, Hospital__c.phoneNumber2__c, Hospital__c.faxNumber1__c, Hospital__c.faxNumber2__c, Hospital__c.chiefOfMedicine__c, Hospital__c.salesRep__c, Hospital__c.teachingHospital__c from Hospital__c where Hospital__c.id__c = :id];
	}
	
	public PageReference goBack(){
    	PageReference Page = new PageReference('/apex/HospitalsList');
	    Page.setRedirect(true);
	    return Page;
    }
    
    public void updateHospital(){
    	HospitalManaging.updateHospital(hospital.id__c, hospital.name__c, hospital.country__c, hospital.town__c, hospital.street__c, hospital.streetNumber__c, hospital.postalCode__c, hospital.phoneNumber1__c, hospital.phoneNumber2__c, hospital.faxNumber1__c, hospital.faxNumber2__c, hospital.chiefOfMedicine__c, hospital.salesRep__c, hospital.teachingHospital__c);
    }
}