objects/Hospital__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>id__c</fullName>
        <label>id</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>name__c</fullName>
        <label>name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Hospital</label>
    <nameField>
        <label>Hospital Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hospitals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HospitalsListController.cls
public with sharing class HospitalsListController {
    public List<Hospital__c> hospitals {get; set;}
    
    public HospitalsListController() {
    	hospitals = [SELECT Hospital__c.id__c, Hospital__c.name__c FROM Hospital__c];
    }
    
    public PageReference goToAddNewHospital(){
    	PageReference Page = new PageReference('/apex/AddNewHospital');
	    Page.setRedirect(true);
	    return Page;
    }
    
    public PageReference goToMainPage(){
    	PageReference Page = new PageReference('/apex/MainPage');
	    Page.setRedirect(true);
	    return Page;
    }
}